import type { Project } from "./types";

const imported = {
  at: "2026-06-15T11:34:30",
  author: "System",
  type: "Imported" as const,
  field: "",
  oldValue: "",
  newValue: "",
  note: "Seed project loaded from PM tracker / ARLM list.",
};

export const seedProjects: Project[] = [
  {
    id: "p_EXT_NIRJAI_01",
    projectNumber: "EXT-NIRJAI-01",
    name: "Calendar Integration",
    projectClass: "Platform Project",
    clientCode: "N/A",
    workBy: "Hybrid",
    externalResources: "HK, Nirjai",
    category: "Integration Project",
    priority: "High",
    size: "S",
    rag: "Red",
    blocker: true,
    helpNeeded: "Vendor",
    owner: "Nirjai",
    targetDate: "",
    lastUpdated: "2026-06-13",
    deliverable:
      "Past events sync fix, sync performance optimization, UI/event visibility improvements, OAuth flow fixes, duplicate event handling, participant sync, and end-to-end QA validation.",
    bottleneck: "Requirements shared; waiting to start feedback work.",
    nextAction: "Plan internal capacity to resume this urgent maintenance stream.",
    actions: [],
    history: [imported],
  },
  {
    id: "p_EXT_NIRJAI_02",
    projectNumber: "EXT-NIRJAI-02",
    name: "EFAX Integration",
    projectClass: "Platform Project",
    clientCode: "N/A",
    workBy: "Hybrid",
    externalResources: "HK, Nirjai",
    category: "Integration Project",
    priority: "High",
    size: "S",
    rag: "Red",
    blocker: true,
    helpNeeded: "Vendor",
    owner: "Nirjai",
    targetDate: "",
    lastUpdated: "2026-06-13",
    deliverable:
      "Document repository faxing, multi-recipient fax support, lifecycle tracking, failed fax logging, audit trail, user history, and status visibility.",
    bottleneck: "Requirements shared; waiting to start feedback work.",
    nextAction: "Prepare an internal fallback plan to deliver the integration.",
    actions: [],
    history: [imported],
  },
  {
    id: "p_EXT_HK_NIRJA_00",
    projectNumber: "EXT-HK/NIRJA-00",
    name: "SharePoint Integration",
    projectClass: "Platform Project",
    clientCode: "N/A",
    workBy: "Internal [Aztute]",
    externalResources: "",
    category: "Integration Project",
    priority: "High",
    size: "L",
    rag: "Red",
    blocker: true,
    helpNeeded: "None",
    owner: "N/A",
    targetDate: "",
    lastUpdated: "2026-06-13",
    deliverable: "SharePoint integration plan and implementation path.",
    bottleneck: "Requirements shared; consultant plan still pending.",
    nextAction: "Find a SharePoint consultant and confirm implementation approach.",
    actions: [],
    history: [imported],
  },
  {
    id: "p_INT_DEV_01",
    projectNumber: "INT-DEV-01",
    name: "E-Sign Integration",
    projectClass: "Platform Project",
    clientCode: "N/A",
    workBy: "Hybrid",
    externalResources: "HK",
    category: "Integration Project",
    priority: "High",
    size: "S",
    rag: "Red",
    blocker: true,
    helpNeeded: "Shobhit sir",
    owner: "Internal",
    targetDate: "",
    lastUpdated: "2026-06-13",
    deliverable:
      "Document signing workflow, multi-document envelopes, signature placement, signer/CC configuration, and provider-agnostic tracking.",
    bottleneck: "Not started because internal capacity is occupied with eligibility and library tickets.",
    nextAction: "Sequence MVP, provider abstraction, webhook tracking, and central dashboard work.",
    actions: [],
    history: [imported],
  },
  {
    id: "p_EXT_HK_01",
    projectNumber: "EXT-HK-01",
    name: "Performance: Lazy Loading",
    projectClass: "Platform Project",
    clientCode: "N/A",
    workBy: "Hybrid",
    externalResources: "HK",
    category: "Performance Project",
    priority: "Urgent",
    size: "S",
    rag: "Yellow",
    blocker: false,
    helpNeeded: "Vendor",
    owner: "HK",
    targetDate: "",
    lastUpdated: "2026-06-13",
    deliverable:
      "Page-level lazy loading plus SurveyJS compatibility fixes for signature and tagbox behavior.",
    bottleneck: "Issue work is tied to the previously completed performance project.",
    nextAction: "Merge to dev after active issues are resolved.",
    actions: [],
    history: [imported],
  },
  {
    id: "p_EXT_HK_05",
    projectNumber: "EXT-HK-05",
    name: "DB Elastic Pool",
    projectClass: "Platform Project",
    clientCode: "N/A",
    workBy: "Hybrid",
    externalResources: "HK",
    category: "Costing Project",
    priority: "High",
    size: "XS",
    rag: "Watch",
    blocker: false,
    helpNeeded: "Vendor",
    owner: "HK",
    targetDate: "",
    lastUpdated: "2026-06-13",
    deliverable:
      "Azure SQL elastic pool configuration, POC migration, capacity recommendation, monitoring, cost comparison, and final recommendation.",
    bottleneck: "Upwork contractor needed.",
    nextAction: "Source and evaluate contractor candidates.",
    actions: [],
    history: [imported],
  },
  {
    id: "p_ARLM_P0",
    projectNumber: "ARLM-P0",
    name: "Billing Rules Engine",
    projectClass: "Platform Project",
    clientCode: "ARLM",
    workBy: "Internal [Aztute]",
    externalResources: "",
    category: "ARLM / Billing & Claims Lifecycle",
    priority: "High",
    size: "M",
    rag: "Watch",
    blocker: false,
    helpNeeded: "Product",
    owner: "Internal",
    targetDate: "",
    lastUpdated: "2026-06-13",
    deliverable:
      "Billing rule model, rate model, priority/effective dating, auth and eligibility hooks, unit/threshold logic, and simulator.",
    bottleneck:
      "Shared rules package touches authorization, charge creation, rate selection, claim packaging, and traceability.",
    nextAction: "Confirm owner, sprint sequencing, and target milestone.",
    actions: [],
    history: [imported],
  },
  {
    id: "p_CLIENT_ONBOARD_01",
    projectNumber: "CL-ONB-01",
    name: "Client Onboarding Workflow",
    projectClass: "Client Project",
    clientCode: "Pilot",
    workBy: "Internal [Aztute]",
    externalResources: "",
    category: "Implementation",
    priority: "Medium",
    size: "M",
    rag: "Green",
    blocker: false,
    helpNeeded: "CS",
    owner: "Implementation",
    targetDate: "",
    lastUpdated: "2026-06-14",
    deliverable:
      "Reusable onboarding checklist, status milestones, client handoff notes, and launch readiness review.",
    bottleneck: "Needs final template review with CS.",
    nextAction: "Schedule CS review and convert accepted template into operating checklist.",
    actions: [],
    history: [imported],
  },
];
